### PR TITLE
Refs #4971 Fix #457. Added Blackbox for it and modified SimpleCommuni… [5205]

### LINKED ISSUE #457: Participant with different lease expiration timeout fail to reconnect [4971]
Given two participants on a network, if both participant have a different participant lease timeout value (for example, one has 120s lease while the other has 360s lease). When the network gets disconnected and the participant with the shorter lease timeout expire, if the network connection is reconnected before the longer lease participant had the opportunity to timeout, then communication cannot be re-established.

### PR DESCRIPTION
**Pull request by LuisGP**
…cation to ease testing.

Fix #457

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1612/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1576/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1587/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1614/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1578/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1589/)

File: test/communication/Subscriber.cpp [hunk 1]
```diff
@@ -33,10 +34,37 @@
...
+
+        /**
+         * This method is called when a new Participant is discovered, or a previously discovered participant changes its QOS or is removed.
+         * @param p Pointer to the Participant
+         * @param info DiscoveryInfo.
+         */
+        void onParticipantDiscovery(Participant*, rtps::ParticipantDiscoveryInfo&& info) override
+        {
+            if(info.status == rtps::ParticipantDiscoveryInfo::DISCOVERED_PARTICIPANT)
+                std::cout << "Subscriber discovered a participant" << std::endl;
```
Comment (richiware) [inline test/communication/Subscriber.cpp]: Apply coding style. I miss brackets.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1628/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1592/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1603/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1632/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1596/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1607/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1655/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1615/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1627/)
